pages:
  title_and_body:
    parts:
      title:
        type: String
      body:
        type: Html
  three_text_columns:
    parts:
      column_one:
        type: Html
      column_two:
        type: Html
      column_three:
        type: Html
  test_template:
    parts:
      text:
        type: string
      content:
        type: html
        label: The content
        description: This is the content

  profile:
    parts:
      avatar:
        type: image
        styles:
          original: 200x200>
          thumb: 50x50>
      about:
        type: html